### ISSUE TITLE
Development, testing, acceptance and production

### ISSUE THREAD

**Issue by kootenpv** [watson-developer-cloud/conversation-simple#149]
I realize it is a bit out of place, but I'm hoping someone here has an answer.

Is it correct to assume that for "development, testing, acceptance and production" we should only make use of 1 Watson Conversation Service, or would it be advisable to use multiple?

**Comment by mitchmason** [comment]
Its really up to you. Lite/Standard instances are free so its no problem to have multiple. I typically don't, I just keep them in a single instance with multiple workspaces, its just easier for us to manage. Most clients do the same. But a few do have multiple instances because they want the separate credentials to avoid any possible confusion or accidental pushing to prod.

**Comment by kootenpv** [comment]
Thanks a lot, I guess it really does depend on multiple factors!
