### ISSUE TITLE
Left side of input text is cut off when highlighted

### ISSUE THREAD

**Issue by tdalbo92** [watson-developer-cloud/conversation-simple#23]
![image](https://cloud.githubusercontent.com/assets/8292003/16746647/4a1889d8-4789-11e6-9d0d-f7d5e29df449.png)

Clicking away from the input field shifts the text to proper alignment.

**Comment by ColbyJohnIBM** [comment]
@tdalbo92 What browser and version was this found in?

**Comment by tdalbo92** [comment]
Chrome, 51.0.2704.106 m (64-bit)

**Comment by tdalbo92** [comment]
On Mac OS X 10.11.  Seems like it doesn't happen in Windows with the same Chrome version, strangely.

**Comment by ColbyJohnIBM** [comment]
This issue exists on the car-dashboard side as well, mostly when the screen has been re-sized, causing issues with the underlining as well. Will fix this soon.

**Comment by ColbyJohnIBM** [comment]
Are you still seeing this on your machine in the simple app? I haven't delivered any changes yet, because we can't reproduce in the simple app (I think the resizing issue in the car-dashboard is independent), so I can't be sure if I've fixed it.

To be fair, we've only tried briefly using the following:
Mac: 10.11.4
Chrome: Version 52.0.2743.82 (64-bit)

**Comment by tdalbo92** [comment]
Hmm - all fixed!  Weird.
