### ISSUE TITLE
Can this conversation have a locale variable?

### ISSUE THREAD

**Issue by ysfAskri** [watson-developer-cloud/conversation-simple#26]
Can this conversation have a locale variable? 
like the [movie dialog & NLC example](https://conversational-agent-application-starter-kit.mybluemix.net/?cm_mc_uid=93222245435914647056951&cm_mc_sid_50200000=1468408401#/) which can storage [my name](https://postimg.org/image/iwvevnypd/)

**Comment by mitchmason** [comment]
This conversation specifically? No. The service itself can easily do that using context variables. See the advanced section of the docs for more info.
https://www.ibm.com/watson/developercloud/doc/conversation/advanced_overview.shtml
Using context you can store and inject pretty much any info you want at any point in the conversation.

**Comment by pablitomelo** [comment]
Using Context the app must send the name to Watson, but how can i get the name in Watson?
For example i want to detect and store "Pablo" in the variable name if the user input "My name is Pablo" How can i archive this? Do i have to use regex in the app?

**Comment by mitchmason** [comment]
Names are exceptionally hard to extract. You could use regex, or potentially another service like Alchemy, but it will likely not catch every single name possible. Typically in conversational apps we do like the "whats in theatres" application and have a starting screen to collect a user's name to be sure we do not get it wrong. The problem is there are no bounds on what a name can be, and add to that people saying simple "Mitch" or "My name is Mitch" or even the grammatically incorrect "my name is mitch" makes this a very difficult problem to solve.
